# Server Config
listen-port: 5901
desktop-name: This is a test

# Controller Config
controller-ip: 10.1.2.1
controller-port: 19509

# Camera Config
use-camera: true
camera-location: /dev/video0
camera-resX: 1280
camera-resY: 720
camera-fps: 30

# Refresh Algorithm Config
use-diff-frames: false # If false send whole frame every frame
mouse-box-size: 50
diffThreshold: 1
minContourArea: 100

# Mouse Config
use-rel-mouse: false # If false use absolute mouse
