# Server Config
listen-port: 5901
desktop-name: VM-Controller

# Controller Config
use-controller: true  # If false handles keyboard and mouse in "dummy mode"
controller-ip: 127.0.0.1  # Ignored in "dummy mode"
controller-port: 19509  # Ignored in "dummy mode"

# Camera Config
use-camera: true  # If false handles display in "dummy mode"
camera-location: /dev/video0  # Ignored in "dummy mode"
camera-resX: 1280
camera-resY: 720
camera-fps: 30  # Ignored in "dummy mode"

# Refresh Algorithm Config
use-diff-frames: false  # If false send whole frame every frame
mouse-box-size: 50  # Ignored if "use-diff-frames" is false
diffThreshold: 1  # Ignored if "use-diff-frames" is false
minContourArea: 100  # Ignored if "use-diff-frames" is false

# Mouse Config
use-rel-mouse: false  # If false use absolute mouse
